### ISSUE TITLE
Mod breaks mipmap

### ISSUE THREAD

**Issue by IronFudge** [Sweenus/SimplySwords#17]
When version 1.34 for fabric 1.19.2 is installed, Minecraft's mipmapping setting seems to be broken and not functioning properly

**Comment by Sweenus** [comment]
Thanks for the report!
This issue will be fixed in version 1.35 (due in a few days).

**Comment by IronFudge** [comment]
Thank you very much! This was the only issue preventing this mod from being a no-brainer install for me.
One other suggestion I have would be creating a config menu within modmenu so the user doesn't have to edit config files directly. I'm not sure how difficult that would be to implement however.

**Comment by Sweenus** [comment]
No worries at all! I've gone ahead and pushed that update to CurseForge ahead of schedule, if you'd like to give it a try :)

In regards to modmenu support - this is actually something I played with in the past. It requires the use of a seperate config mod, and wasn't able to get it working. I've since expanded on the existing config system heavily, so to take another swing at it at this stage would be a huge time investment that I'm just not able to dedicate to it, unfortunately.

I'm going to close this ticket as the mipmap bug should be fixed - if you run into any further issues please do feel free to make another ticket!
