### ISSUE TITLE
Soulrender

### ISSUE THREAD

**Issue by blakreaper** [Sweenus/SimplySwords#32]
ok so i got Soulrender in a chest all fine, i dont know if its supposed to but every first strike deals 4 damage and the second strike deals the correct 10 damage, when using for example a torch on the second hand the weapon only does the first strikeso it ends up dealing almost no damage compared

**Comment by Sweenus** [comment]
Hey there,

This isn't a bug, rather a technical limitation of the pose system in Better Combat.
The item needs to be treated as a one-handed weapon in order to use an idle pose.

As this weapon is intended to be a two-handed weapon, I've lowered the damage initial one-handed swing, and doubled the damage of the follow-up two-handed swing to make up for the lost damage on the first hit.

This isn't ideal, and the alternative is to get rid of the idle animation on this scythe altogether and make it a true two-handed weapon.

**Comment by jonask028** [comment]
Oh, so that's why it did no damage. please just make it a two hander or reduce the damage, i've been frustrated not knowing why it wasn't dealing damage while offhanding a torch and had to hit zombies 15 times and rely on the right click ability, which restores very little health imo, to deal any real damage.

**Comment by jonask028** [comment]
also the idle animation just looks awkward to me. not really sure why you chose an idle pose over user clarity.
