### ISSUE TITLE
[Suggestion] Mod compat

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Sweenus/SimplySwords#37]
**[Expert weapons and tools mod](https://www.curseforge.com/minecraft/mc-mods/expert-weapons) makes it so that progression is slowed down.** 
-Gobber - which has compat with simply swords - already has compat with.
-Advanced netherite also has compat. 

[**Better Netherite**](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite-fabric) -which adds in higher levels of weapons/tools/armor above netherite, some with their own abilities- Support.

**Comment by Sweenus** [comment]
Hey there,

I do really like the idea of Expert weapons compat, however... with three individual parts per weapon, multiplied by 15 weapon variants, multiplied by the 28 Ores Simply Swords supports, we're talking about 1,260 individual textures, items, and recipes. It also makes any future additions of weapon variants very painful. I just don't have it in me 🤯

Better Netherite compat, however, is already being worked on by KodoDenka in this third party mod: https://www.curseforge.com/minecraft/mc-mods/knaves-needs

**Comment by DanMeadWasTaken** [comment]
Hmm alright, I hadn't thought of that- that is a bit of a big ask. 
What if someone made the textures for you? I'd be able to do it myself with just a set of templates and initial instructions?

**Comment by DanMeadWasTaken** [comment]
Also, I hadn't thought of this before, but if not expert weapons and tools compat, what about working with [forgero](https://www.curseforge.com/minecraft/mc-mods/forgero) for compat with them? I've also mentioned this to them, as their working hard on not only making the mod as compatible as possible with other mods but to be as functional as possible. #SigmundGranaas/forgero#462


I'd still be more than happy to help out with making textures for expert weapons and tools compat if that's alright? (Still would just need some basic instructions and some templates)

**Comment by DanMeadWasTaken** [comment]
So, i did some research- and it looks like, even if not added to the mod directly, i could possibly use something like kubejs to add it to my pack myself. Which leads me to my final question. Is simply swords recipes able to be modified by kubejs? or by datapack recipes?

**Comment by Sweenus** [comment]
Hmmm, I would need to become a bit more familiar with forgero to know if this is something I can realistically add compat for.
I'll take a look at it when I get a moment.

The recipes can absolutely be modified with datapacks, and I assume kubejs (I know nothing of kubejs).

**Comment by Sweenus** [comment]
Do you happen to know if Forgero requires textures to be made for each of these individual weapon parts (like the Expert Weapons mod), or is it using some kind of texture stitching code to achieve this?
I can't tell from a glance at thier CF and Github page.

If it's the latter that will make it much easier to add compat for.

**Comment by DanMeadWasTaken** [comment]
Well let's ask em! [lol](https://github.com/SigmundGranaas/forgero/issues/462#issuecomment-1436163612)

**Comment by SigmundGranaas** [comment]
Forgero needs individual template textures for each part used in a weapon. It combines templates with material palettes to create textured parts. This makes it possible to let the system generate the bulk of the parts, and only focus on having all of the templates for the unique parts available. Textures for different parts that are fits together are then combined by the system when crafted, so no need to worry about that either. Autogenerated parts have to follows specific rules for how they are generated, so it is not currently possible to create accents or too much detail in each part. It is encouraged to take advantage of the upgrade/slot system to add additional "layers" to parts to add more detail.

Still, autogenerated parts aren't always good enough, so it's also possible to override all textures with hand-crafted ones. Due to the time required to create part textures manually (Like in your case), it's only recommended to do this in places where the handmade one is far superior to the generated one.

Forgero has some current limitations with tools that are longer than vanilla ones, due do not being able to switch between models based on where it's rendered (Inventory, hand, 3rd person), but this is going to be fixed soon hopefully. All bettercombat configurations should also be able to carry over without too much of an issue.

Anyways, you have made an awesome mod, and I think your weapons look awesome! I would be be very happy to support in an effort to add compatibility for our mods. Forgero is based completely on datapacks, so no code should technically be required, and everything will be picked up automatically if set up correctly. Due to the fact that using templates from your assets would be needed, I think it would be best to keep the compatibility here, so there's no issues with licencing. Forgero would likely have to make some internal changes/additions to fully support the functionality of your weapons, but that's just an improvement to the system in my eyes.

**Comment by Sweenus** [comment]
Wow, thank you for the very detailed response! This tells me everything I need to know to get started.
That's fantastic to hear that you've gone with a templated approach - this makes adding compatibility significantly more enticing.

I'll start learning up on Forgero in-game and will then take a look at compatibility once I understand the mod a bit better.
I've popped into the Forgero discord and will reach out to you there with any questions I may have once I get the project underway, if that's not a bother.

Thanks again for that very detailed breakdown! Looking forward to see what kind of compatibility we can build 🙂

**Comment by SigmundGranaas** [comment]
No problem! Great to hear you're interested. Unfortunately, documentation for the how to create these packs is far from finished, but we have some channels on the discord where we discuss them. Don't be afraid to reach out if there's something you have trouble with or if you're wondering about something. I'm here to help! 

As a side note, some big updates to the tooltip and a lot more bugfixes are being worked on in v0.10.7 which is in a RC stage right now, and hopefully will have a full release soon. This will hopefully clear up a lot of the confusion that you will inevitably run into when trying to figure out what certain materials do when combined together, as there is a near complete lack of information about this in the current version.
