### ISSUE TITLE
Mythic Metals Compat Crash

### ISSUE THREAD

**Issue by Noaaan** [Sweenus/SimplySwords#76]
Hey, there seems to be some issue regarding with the compatability between Mythic Metals and Simply Swords. 
A user reported a crash to me yesterday (from https://github.com/Noaaan/MythicMetals/issues/172)
Could you give some advice on what is going wrong here?

https://github.com/Noaaan/MythicMetals/files/11647446/crash-2023-06-05_00.04.09-client.txt

**Comment by Sweenus** [comment]
Sorry for the delay in response Noaaan!

It looks to be a crash relating to a mixin I have that is injecting some of my mod init into Mythic Metals to get around Fabric load order jank. The only previous reports of this issue were Quilt specific, and were fixed.

I'm unable to replicate this issue using the same versions of Minecraft, Simply Swords, Mythic Metals, and Architectury, and the latest Fabric (0.14.21), so I'm not sure what could be causing this issue. The best course of action for this user for now is probably to remove Simply Swords from their pack.

You had mentioned to me previously that the only requirement for the Mythic Metals innate powers (Carmot looting, Prometheum repairs) were that the items were in the correct tag files. Does this mean that the mixins I have to your Ability class server only to add tooltip information? If so, it may be worth me revising how I handle compatibility so that we don't run into any mixin issues in the future.

**Comment by Sweenus** [comment]
Hey Noaaan,

I've cleaned up the compat for Mythic Metals quite a lot in this latest release (1.48.0) and it should be much more stable 🙂
Please let me know if there are any further issues
